apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nestjs-bull
  name: nestjs-bull
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nestjs-bull
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nestjs-bull
    spec:
      containers:
        - image: fabodhub/nestjs-bull:latest
          env:
            - name: REDIS_HOST
              value: nestjs-bull-redis-master
            - name: REDIS_PORT
              value: '6379'
          name: nestjs-bull
          ports:
            - containerPort: 3000
          resources: {}
status: {}
